### ISSUE TITLE
Is there a way to get toolbar at the bottom?

### ISSUE THREAD

**Issue by goodmite** [sibiraj-s/ngx-editor#131]
After writing a long content in the editor, the user will have to go to the top everytime they want to use the toolbar. Is there any setting in the config so that I can get the toolbar at the bottom as well.
Thanks.

**Comment by Olubunmi-Odeyinka** [comment]
I am really interested in this feature too. Can you look into it. Thank you

**Comment by Sibiraj-S** [comment]
I understand but I have to wait while other things are done.

**Comment by sibiraj-s** [comment]
You can put CSS to do that. 

```
display: flex;
flex-direction: colum-reverse;
```

Since v5

```scss

.NgxEditor-Wrapper {
  display: flex;
  flex-direction: column-reverse;

  .NgxEditor-MenuBar {
      border-bottom: none;
      border-top: 1px solid #ccc;
    }
}
```
