### ISSUE TITLE
[Feature request]: Add support for background css variables

### ISSUE THREAD

**Issue by DywiTom** [sibiraj-s/ngx-editor#543]
### Proposal

Hello!

First of all, thanks for your great work!
Especially in the dark theme there are some style problems.
Can you add support for background css variables, please?

```scss
@use 'sass:map';
@use '@angular/material' as mat;

@mixin color($theme) {
  $primary-300: mat.get-theme-color($theme, primary, 300);
  $accent-500: mat.get-theme-color($theme, accent, 500);
  $background-selected-button: mat.get-theme-color($theme, background, selected-button);
  $background-background: mat.get-theme-color($theme, background, background);
  $background-hover: mat.get-theme-color($theme, background, hover);

  ngx-editor-menu {
    --ngx-editor-menu-item-active-color: #{$accent-500};
    --ngx-editor-menu-item-hover-bg-color: #{$background-hover};
    --ngx-editor-menu-item-active-bg-color: #{$background-selected-button};
    --ngx-editor-seperator-color: #ccc;
    --ngx-editor-focus-ring-color: #{accent-500};

    .NgxEditor__Popup,
    .NgxEditor__Dropdown--DropdownMenu {
      background-color: $background-background;
    }

    .NgxEditor__Dropdown:hover,
    .NgxEditor__Dropdown--Item:hover {
      background-color: $background-hover;
    }

    .NgxEditor__Dropdown--Item.NgxEditor__Dropdown--Active {
      background-color: $background-selected-button;
    }
  }
}

@mixin theme($theme) {
  @if mat.theme-has($theme, color) {
    @include color($theme);
  }
}
```

Thank you.

### Willing to submit a PR?

None
