### ISSUE TITLE
[Feature request]: Remove "!important" from --ngx-editor-click-pointer And add :not(:disabled) or add a second var for :disabled

### ISSUE THREAD

**Issue by DywiTom** [sibiraj-s/ngx-editor#546]
### Proposal

Hello!

See title. Thanks :)

```scss
.NgxEditor__MenuBar button, .NgxEditor__MenuBar [role=button] {
  cursor: var(--ngx-editor-click-pointer, default) !important;
}
```

### Willing to submit a PR?

None
